project/config/routes.rb
UserReady::Application.routes.draw do
  resources :locations

  resources :tours

  resources :profiles

  resources :purchases

  resources :registered_users

  resources :webusers

  devise_for :users

  resources :home
  root :to => "home#index"
end

project/app/models/registered_user.rb
class RegisteredUser < Webuser
	has_one :profile
end

project/app/controllers/registered_users_controller.rb
class RegisteredUsersController < ApplicationController
  before_action :set_registered_user, only: [:show, :edit, :update, :destroy]

  # GET /registered_users
  # GET /registered_users.json
  def index
    @registered_users = RegisteredUser.all
  end

  # GET /registered_users/1
  # GET /registered_users/1.json
  def show
  end

  # GET /registered_users/new
  def new
    @registered_user = RegisteredUser.new
  end

  # GET /registered_users/1/edit
  def edit
  end

  # POST /registered_users
  # POST /registered_users.json
  def create
    @registered_user = RegisteredUser.new(registered_user_params)

    respond_to do |format|
      if @registered_user.save
        format.html { redirect_to @registered_user, notice: 'Registered user was successfully created.' }
        format.json { render action: 'show', status: :created, location: @registered_user }
      else
        format.html { render action: 'new' }
        format.json { render json: @registered_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registered_users/1
  # PATCH/PUT /registered_users/1.json
  def update
    respond_to do |format|
      if @registered_user.update(registered_user_params)
        format.html { redirect_to @registered_user, notice: 'Registered user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @registered_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registered_users/1
  # DELETE /registered_users/1.json
  def destroy
    @registered_user.destroy
    respond_to do |format|
      format.html { redirect_to registered_users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registered_user
      @registered_user = RegisteredUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registered_user_params
      params.require(:registered_user).permit(:name)
    end
end

project/app/helpers/registered_users_helper.rb
module RegisteredUsersHelper
end

project/app/views/registered_users/_form.html.erb
<%= form_for(@registered_user) do |f| %>
  <% if @registered_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registered_user.errors.count, "error") %> prohibited this registered_user from being saved:</h2>

      <ul>
      <% @registered_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project/app/views/registered_users/edit.html.erb
<h1>Editing registered_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @registered_user %> |
<%= link_to 'Back', registered_users_path %>

project/app/views/registered_users/index.html.erb
<h1>Listing registered_users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @registered_users.each do |registered_user| %>
      <tr>
        <td><%= registered_user.name %></td>
        <td><%= link_to 'Show', registered_user %></td>
        <td><%= link_to 'Edit', edit_registered_user_path(registered_user) %></td>
        <td><%= link_to 'Destroy', registered_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registered user', new_registered_user_path %>

project/app/views/registered_users/new.html.erb
<h1>New registered_user</h1>

<%= render 'form' %>

<%= link_to 'Back', registered_users_path %>

project/app/views/registered_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @registered_user.name %>
</p>

<%= link_to 'Edit', edit_registered_user_path(@registered_user) %> |
<%= link_to 'Back', registered_users_path %>